# Generated by Django 4.2 on 2024-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0004_delete_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greeting',
            old_name='message',
            new_name='ip_in_machine',
        ),
        migrations.AddField(
            model_name='greeting',
            name='ip_out_machine',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
