# Generated by Django 4.2 on 2024-04-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0005_rename_message_greeting_ip_in_machine_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greeting',
            new_name='SetIP',
        ),
    ]
