# Generated by Django 4.2 on 2024-04-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0006_rename_greeting_setip'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
