# Generated by Django 5.1.2 on 2024-11-06 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0008_contacts_delete_setip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerIP',
        ),
    ]
