# Generated by Django 5.1.2 on 2024-11-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0009_delete_serverip'),
    ]

    operations = [
        migrations.CreateModel(
            name='is_connected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_login', models.BooleanField()),
            ],
        ),
    ]
