# Generated by Django 5.1.2 on 2024-11-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0010_is_connected'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='is_connected',
            new_name='WhatsappConnect',
        ),
    ]
