# Generated by Django 5.1.2 on 2024-11-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0011_rename_is_connected_whatsappconnect'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_time', models.BooleanField()),
            ],
        ),
    ]
